name: main

on:
  schedule:
    - cron: "0 */24 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running tests..."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token for actions

  generate-snake-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake Game
        run: |
          echo "Generating snake game..."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token for actions
          GITHUB_USER_NAME: RichardLechko # Username for generating the game

      - name: Ensure Generated Files Exist
        run: |
          echo "Checking generated files..."

  deploy-ghpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        run: |
          echo "Deploying to GitHub Pages..."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token for deployment
