name: CI/CD Pipeline

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20

      # Step 3: Install dependencies
      - run: yarn install --frozen-lockfile

      # Step 4: Run TypeScript checks, linting, and tests
      - run: |
          npm run type
          npm run lint
          npm run test --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Step 5: Build demo (if applicable)
      - run: npm run build:demo
        env:
          GITHUB_USER_CONTRIBUTION_API_ENDPOINT: https://snk-one.vercel.app/api/github-user-contribution/

      # Step 6: Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: packages/demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
